sudo: required  
dist: trusty
language: node_js
addons:
  chrome: stable
node_js:  
  - "8.1.2"
before_install:
  - export PATH=./node_modules/.bin:$PATH
install:
  - npm install
  - npm link
before_script:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test:once
  - npm run e2e
  - npm run build
